### ISSUE TITLE
Problem solutions

### ISSUE THREAD

**Issue by insolitum** [insolitum/problem_solutions#1]
You can add solutions if it's not on the list or differs from already added solutions (different programming language or approach)  so that people can learn from each other's code.

**Comment by recksoldier** [comment]
hackerearth supported?

**Comment by daweedkob** [comment]
Sure, any website is supported. The more, the better.

**Comment by Kejosue** [comment]
https://github.com/actions/runner-images/issues/6796#issue-1501014615
