### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by devfinwiz** [insolitum/problem_solutions#15]
Hey, will it be okay if I contribute to a few problems here?

**Comment by insolitum** [comment]
Hello, sure.

**Comment by devfinwiz** [comment]
Want me to continue in the same format (only 1 code file) or a folder which is well organised for each problem would do?

**Comment by devfinwiz** [comment]
Hey, could you keep merging my PRs on your repository? I'll be trying to
contributing every week, kindly merge the open PRs whenever you see any.
Thanks!
